<pre class='metadata'>
Title: Go language binding for Web IDL
Shortname: WebIDL-Go
Status: DREAM
Repository: jcbhmr/WebIDL-Go
URL: https://jcbhmr.me/WebIDL-Go/
Editor: Jacob Hummer, jcbhmr@outlook.com, https://jcbhmr.me/
Abstract: Outline conventions & ideas for mapping Web IDL concepts & types into native Go patterns, conventions, and types.
Markup Shorthands: markdown yes, css no
</pre>

# Goals # {#goals}

Introduction here.
