name: deploy-pages
on:
  push:
    branches: "main"
    paths-ignore:
      - README.md
      - LICENSE*
      - .gitignore
      - .devcontainer/**
      - .github/**
      - "!.github/workflows/deploy-pages.yml"
  workflow_dispatch:
concurrency: ${{ github.workflow }}
jobs:
  deploy-pages:
    permissions:
      pages: write
      id-token: write
      deployments: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install pipx
      - run: pipx install bikeshed
      - id: configure-pages
        uses: actions/configure-pages@v4
      - run: bikeshed spec
        env:
          BASE_URL: ${{ steps.configure-pages.outputs.base_url }}/
          BASE_PATH: ${{ steps.configure-pages.outputs.base_path }}/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - id: deploy-pages
        uses: actions/deploy-pages@v4
